name: "git-tag-check-action"
description: "Check git tag is exists or not"
author: "bbonkr"
branding:
  color: purple
  icon: check
inputs:
  tag:
    required: true
    description: "Tag"
  github_token:
    required: true
    description: "GitHub Personal Access Token. It requires REPO scope."
  owner:
    required: false
    description: "Name of repository owner, For test. You does not need this input."
    default: ""
  repo:
    required: false
    description: "Repository name; For test. You does not need this input."
    default: ""
  prefix:
    required: false
    description: "Tag prefix"
    default: ""
outputs:
  tag:
    description: "If tag is exists, returns tag. Does not exist then empty string."
  version:
    description: "Version string. Same as tag."
  major:
    description: "Major number of version"
  minor:
    description: "Minor number of version"
  patch:
    description: "Patch number of version"
  prerelease:
    description: "Pre-release value of version"
  build:
    description: "Build value of version"
runs:
  using: "node20"
  main: "dist/index.js"
