name: 'Verify PR'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - run: |
          npm install
      - run: |
          npm run all
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          OWNER: ${{ secrets.OWNER }}
          REPO: ${{ secrets.REPO }}

      - uses: ./
        id: git_tag_check
        with:
          tag: 'v1.0.0'
          github_token: ${{ secrets.GH_TOKEN }}
      - name: log
        run: |
          echo "${{ steps.git_tag_check.outputs.tag }}"
