name: "Verify PR"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: |
          npm install

      - name: Test
        run: |
          npm run test --if-present
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          OWNER: ${{ secrets.OWNER }}
          REPO: ${{ secrets.REPO }}

      - name: npm all script
        run: |
          npm run all

      - uses: ./
        id: git_tag_check
        with:
          tag: "v1.0.0"
          github_token: ${{ secrets.GH_TOKEN }}

      - name: log
        run: |
          echo "tag=${{ steps.git_tag_check.outputs.tag }}"
          echo "version=${{ steps.git_tag_check.outputs.version }}"
          echo "version=${{ steps.git_tag_check.outputs.major }}"
          echo "version=${{ steps.git_tag_check.outputs.minor }}"
          echo "version=${{ steps.git_tag_check.outputs.patch }}"
